name: NewRelic ECS Release Markers
description: Reads a Task Definition and sends a release marker to NewRelic

inputs:
  run-in-container:
    description: (Bool) Whether to run the command inside of the docker container
    required: false
  output-file:
    description: The output file
    required: true
  args:
    description: Additional arguments
    required: false

outputs:
  error-count:
    description: Number of errors found
    value: ${{ steps.phpstan.outputs.error-count }}
  results-md:
    description: A markdown representation of the results for PR comments or emails
    value: ${{ steps.phpstan-markdown.outputs.results-md }}
runs:
  using: 'composite'
  steps:
    - if: inputs.run-in-container
      name: Run PHPStan In container
      uses: speareducation/action-docker-exec@main
      with:
        command: 'vendor/bin/phpstan --memory-limit=1G --error-format=json ${{ inputs.args }} > ${{ inputs.output-file }} || :'
    - if: '!inputs.run-in-container'
      name: Run PHPStan
      shell: bash
      run: bash -c 'vendor/bin/phpstan --memory-limit=1G --error-format=json ${{ inputs.args }} > ${{ inputs.output-file }} || :'
    - name: Process Results
      id: phpstan
      shell: bash
      run: |
        errorCount=$(jq -r .totals.file_errors ${{ inputs.output-file }})
        echo "errorCount=$errorCount" >> ${GITHUB_OUTPUT}

    # TODO: Update this to be pretty markdown
    - name: Generate Markdown
      id: phpstan-markdown
      shell: bash
      run: |
        tmpFile=$(mktemp)
        echo '# PHPStan Results' >> $tmpFile
        cat ${{ inputs.output-file }} | jq -r '.files | to_entries | map(
          ("**" + (.key|tostring) + "**"),
          (
            .value.messages | map(
              ("- Line " + (.line|tostring) + ": " + (.message|tostring))
            )[]
          ),
          ""
        )[]' >> $tmpFile
        echo "results-md<<EOT" >> ${GITHUB_OUTPUT}
        cat $tmpFile >> ${GITHUB_OUTPUT}
        echo "EOT" >> ${GITHUB_OUTPUT}
